history/urls.py
from django.urls import path
from . import views

app_name = "history"
urlpatterns = [
    path("lookup/", views.lookup, name="lookup"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("report/", views.report, name="report"),
    path("delete/", views.delete, name="delete"),
    path("report-details/", views.report_details, name="report_details"),
    path("update-report-status/", views.update_report_status, name="update_report_status"),
    path('set_timezone/', views.set_timezone, name='set_timezone'),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("login_request/", views.login_request, name="login_request"),
]

shared/urls.py
from django.urls import path
from . import views

app_name = "shared"
urlpatterns = [
    path("", views.home, name="home"),
    path("reports/admin", views.admin_report_list, name="admin_report_list"),
    path("render_object_from_s3/<path:s3_object_url>", views.render_object_from_s3, name="render_object_from_s3"),
]

whistleblower_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('submit/', include('submit.urls')),
    path('login/', include('login.urls')),
    path('history/', include('history.urls')),
    path('accounts/', include('allauth.urls')),
    path('', lambda request: redirect('home/', permanent=True)),
    path('home/', include('shared.urls')),
    ]

history/models.py
from django.db import models

# Create your models here.

history/forms.py
from django import forms
from shared.models import Report, User


class CaseSearchForm(forms.Form):
    report_hash = forms.UUIDField(label="Case ID",
                                  widget=forms.TextInput(attrs={'placeholder': 'Enter Your Case ID Here',
                                                                'class': 'form-control',
                                                                'required': True}))

    class Meta:
        model = Report
        fields = ["report_hash"]
        labels = {"id": "Case ID"}
        widgets = {
            'id': forms.TextInput(attrs={'placeholder': 'Case ID',
                                         'class': 'form-control',
                                         'required': True})
        }

history/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shared.models import Report
from .forms import CaseSearchForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.utils import timezone
from django.http import JsonResponse


def lookup(request):
    if request.method == "POST":
        form = CaseSearchForm(request.POST)
        if form.is_valid():
            uuid = form.cleaned_data['report_hash']
            report = get_object_or_404(Report, report_hash=uuid)
            return render(request, "history/report_details.html", {"report": report})
        else:
            return render(request, "history/lookup.html", {'form': form, 'error': "Invalid case ID"})
    else:
        form = CaseSearchForm()
        return render(request, "history/lookup.html", {'form': form})

@login_required
def dashboard(request):
    profile = request.user.profile
    user = request.user
    if user.is_superuser:
        reports = Report.objects.filter(user=user)
    elif hasattr(user, 'profile') and profile.is_admin:
        reports = Report.objects.all()
    else:
        reports = Report.objects.filter(user=user)

    current_timezone = timezone.get_current_timezone_name()

    return render(request, "history/dashboard.html", {'reports': reports, 'current_timezone': current_timezone}, )


@login_required
@require_POST
def report(request):
    report_id = request.POST.get('report_id')
    if not report_id:
        return redirect("history:dashboard")

    report_model = get_object_or_404(Report, id=report_id)

    if request.user.profile.is_admin:
        if "notes" in request.POST:
            report_model.report_text = request.POST.get("notes")
            report_model.save()
            return redirect("history:report", id=report_model.id)

        if "change_status_to_pending" in request.POST and report_model.status == "NEW":
            report_model.status = "PENDING"
            report_model.save()

    request.session['viewing_report_id'] = str(report_model.id)
    return redirect("history:report_details")


@login_required
@require_POST
def update_report_status(request):
    report_id = request.POST.get('report_id')
    if not report_id:
        return redirect('history:dashboard')

    # handles whatever status is passed in the POST request e.g. 'REJECTED' or 'APPROVED'
    report = get_object_or_404(Report, id=report_id)
    if request.user.profile.is_admin:
        if 'status' in request.POST:
            report.status = request.POST.get('status')
            report.save()
            messages.success(request, "Status updated successfully.")
            request.session['viewing_report_id'] = str(report.id)
            return redirect('history:report_details')
        elif "notes" in request.POST:
            report.report_text = request.POST.get("notes")
            report.save()
            messages.success(request, "Notes added successfully.")
            request.session['viewing_report_id'] = str(report.id)
            return redirect("history:report_details")
    return redirect('history:report_details')


def report_details(request):
    report_id = request.session.get('viewing_report_id')
    if not report_id:
        # Handle case where no report ID is found in the session?
        return redirect("history:dashboard")

    report_model = get_object_or_404(Report, id=report_id)
    current_timezone = timezone.get_current_timezone_name()
    del request.session['viewing_report_id']
    return render(request, "history/report_details.html",
                  {"report": report_model, 'current_timezone': current_timezone})


@login_required
@require_POST
def delete(request):
    report_id = request.POST.get('report_id')
    if report_id:
        report = get_object_or_404(Report, id=report_id)
        report.delete()
        return redirect("history:dashboard")
    else:
        return redirect("history:dashboard")

    #  REFERENCES


#  AI Agent: ChatGPT4
#  Date: 2024-4-25
# Prompt: "how can I access a user's local timezone without manually prompting them for it in a Django project and send it to the server for processing and displaying a datetime?"
def set_timezone(request):
    if request.method == 'POST':
        timezone = request.POST.get('timezone')
        if timezone:
            request.session['django_timezone'] = timezone
            # print("Timezone received and set:", timezone)
            return JsonResponse({'status': 'success', 'message': 'Timezone updated.'})
        else:
            return JsonResponse({'status': 'error', 'message': 'No timezone provided.'}, status=400)
    return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)

history/templates/history/dashboard.html
{% extends "submit/base.html" %}
{% load static %}

{% block title %}Reports Dashboard | Hoos Reporting Honor{% endblock %}

{% block main %}
    <h1>Completed Reports</h1>

    <table class="table table-hover table-responsive">
        <thead class="table-dark">
        <tr>
            <th scope="col">Case ID</th>
            <th scope="col">Submitted By</th>
            <th scope="col">Status</th>
            <th scope="col">Date ({{ current_timezone }})</th>
            <th scope="col">Files</th>
        </tr>
        </thead>
        <tbody>
        {% for report in reports %}
            <tr>
                <td>
                    <span class="hash-cell">{{ report.report_hash }}</span>
                </td>
                <td>
                    {% if report.user %}
                        {{ report.user.username }}
                    {% else %}
                        Anonymous
                    {% endif %}
                </td>
                <td>{{ report.status }}</td>
                <td>{{ report.submission_date }}</td>
                <td>
                    <form method="POST" action="{% url 'history:report' %}">
                        {% csrf_token %}
                        <input type="hidden" name="report_id" value="{{ report.id }}">
                        <input type="hidden" name="change_status_to_pending" value="true">
                        <button type="submit" class="btn btn-primary btn-sm">View Report</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

history/templates/history/lookup.html
{% extends 'submit/base.html' %}
{% block title %}Lookup | Hoos Reporting Honor{% endblock %}
{% block main %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="text-center">
            <h4 class="pb-1">To access details to any report that you have submitted while logged in to your account or
                anonymously, please input the Case ID that was displayed after you submitted the report.</h4>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.report_hash }}
                    {% if form.report_hash.errors %}
                        <div class="alert alert-danger">
                            {{ form.report_hash.errors }}
                        </div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

history/templates/history/report_details.html
{% extends 'submit/base.html' %}
{% block title %}Report Details | Hoos Reporting Honor{% endblock %}

{% block extra_css %}
    <link href="../../static/history/report-detail-labels.css" rel="stylesheet">
{% endblock %}

{% block main %}

    <h1>Report {{ report.report_hash }}</h1>

    <h3><span class="label-bold">Report Logistics</span></h3>
    <p><span class="label-bold">User:</span>
        {% if report.user %}
            {{ report.user.username }}
        {% else %}
            Anonymous
        {% endif %}
    </p>
    <p><span class="label-bold">Submission Date ({{ current_timezone }}):</span> {{ report.submission_date }}</p>
    <p><span class="label-bold">Edit Date ({{ current_timezone }}):</span> {{ report.edit_date }}</p>
    <p><span class="label-bold">Status:</span> {{ report.status }}</p>

    <h3><span class="label-bold">Incident Details</span></h3>
    <p><span class="label-bold">Incident Date:</span> {{ report.incident_date }}</p>
    <p><span class="label-bold">Incident Location:</span> {{ report.incident_location }}</p>
    <p><span class="label-bold">Students Involved:</span> {{ report.students_involved }}</p>
    <p><span class="label-bold">Report Summary:</span> {{ report.report_summary }}</p>

    <h3><span class="label-bold">Associated Files</span></h3>
    <ul>
        {% if report.file_set.all %}
            {% for file in report.file_set.all %}
                <li>
                    <a href="{% url 'shared:render_object_from_s3' s3_object_url=file.get_file_url %}"
                       target="_blank">{{ file.file.name }}</a>
                </li>
            {% endfor %}
        {% else %}
            <li>No associated files.</li>
        {% endif %}
    </ul>

    <h3><span class="label-bold">Admin Feedback</span></h3>
    <p><span class="label-bold">Admin Notes:</span>
        {% if report.report_text %}{{ report.report_text }}{% else %}No feedback{% endif %}</p>

    {% if user.profile.is_admin %}
        <div>
            <form action="{% url 'history:update_report_status' %}" , method="post">
                {% csrf_token %}
                <input type="hidden" name="report_id" value="{{ report.id }}">
                <input type="text" id="notes" name="notes" class="form-control" placeholder="Notes"/>
                <div style="margin-top: 10px;">
                    <button type="submit" class="btn btn-primary" m>Save Admin Notes</button>
                </div>
            </form>
        </div>

        <div style="margin-top: 10px;">
            <form action="{% url 'history:update_report_status' %}" , method="post">
                {% csrf_token %}
                <input type="hidden" name="report_id" value="{{ report.id }}">
                <input type="hidden" name="status" value="APPROVED">
                <button type="submit" class="btn btn-success">Approve</button>
            </form>
        </div>

        <div style="margin-top: 10px;">
            <form action="{% url 'history:update_report_status' %}" , method="post">
                {% csrf_token %}
                <input type="hidden" name="report_id" value="{{ report.id }}">
                <input type="hidden" name="status" value="REJECTED">
                <button type="submit" class="btn btn-warning">Reject</button>
            </form>
        </div>
    {% endif %}

    <div style="margin-top: 10px; margin-bottom: 10px">
        <form method="POST" action="{% url 'history:delete' %}">
            {% csrf_token %}
            <input type="hidden" name="report_id" value="{{ report.id }}">
            <button type="submit" class="btn btn-danger"
                    onclick="return confirm('Are you sure you want to delete this report?');">Delete
            </button>
        </form>
    </div>
{% endblock %}